global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'danielqsj-kafka-exporter'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['danielqsj-kafka-exporter:9308']

  - job_name: 'seglo-kafka-lag-exporter'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['seglo-kafka-lag-exporter:8000']
